"""Multi-Round Iterative Retrieval Engine.

Each round is purposeful and directed — its queries are generated by the LLM
based on all prior findings.  The engine produces structured outputs that feed
into the next round's query generation.
"""

from __future__ import annotations

import logging
from typing import AsyncIterator

from ..core.config import settings
from ..core.llm import chat_completion_json
from ..core.models import (
    Entity,
    EventFraming,
    Relationship,
    RetrievalQuery,
    RetrievalRoundResult,
    Source,
)
from .search import web_search

logger = logging.getLogger(__name__)

# Round focus areas (default schedule — LLM may adjust)
ROUND_FOCUS = [
    "Timeline & verified facts",
    "Key actors & organisations",
    "Historical context & patterns",
    "Hidden connections & networks",
    "Cross-domain connections (economic, military, legal)",
]

QUERY_GEN_SYSTEM = """\
You are a research strategist for an intelligence analysis platform.
Given the event framing and all prior retrieval findings, generate targeted
search queries for the current retrieval round.

Current round focus: {focus}

Return a JSON object:
{{
  "queries": [
    {{"query": "<search query text>", "rationale": "<why this query>"}},
    ...
  ]
}}

Rules:
- Generate 3-5 queries per round.
- Queries must be specific, not generic.
- Each query should target a different angle of the focus area.
- Build on what was found in prior rounds — avoid repeating searches.
"""

ROUND_SUMMARY_SYSTEM = """\
You are an intelligence research analyst.  Given the search results below,
produce a structured summary for this retrieval round.

Return a JSON object:
{{
  "findings_summary": "<2-3 paragraph summary of key findings>",
  "new_entities": [
    {{"name": "<entity>", "entity_type": "<person|organization|location|event|legislation|financial_instrument>", "description": "<brief>"}},
    ...
  ],
  "new_relationships": [
    {{"source_entity": "<name>", "target_entity": "<name>", "relationship_type": "<owns|controls|funds|opposes|influences|allied_with|member_of|subsidiary_of|located_in|participated_in|related_to>", "description": "<brief>"}},
    ...
  ],
  "next_round_triggers": ["<question or lead for the next round>", ...]
}}

Be thorough but precise.  Only include entities that are directly relevant.
"""


async def run_retrieval(
    framing: EventFraming,
    max_rounds: int | None = None,
    on_progress: callable | None = None,
) -> AsyncIterator[RetrievalRoundResult]:
    """Run iterative retrieval rounds, yielding results as they complete."""

    num_rounds = min(max_rounds or settings.max_retrieval_rounds, len(ROUND_FOCUS))
    prior_findings: list[str] = []
    all_entities: list[Entity] = []

    for round_num in range(1, num_rounds + 1):
        focus = ROUND_FOCUS[round_num - 1] if round_num <= len(ROUND_FOCUS) else "Gap-filling & verification"

        if on_progress:
            await on_progress(f"Round {round_num}/{num_rounds}: {focus}")

        # --- 1. Generate queries ---
        context = _build_context(framing, prior_findings, all_entities)
        query_prompt = QUERY_GEN_SYSTEM.format(focus=focus)
        queries_data = await chat_completion_json(
            system_prompt=query_prompt,
            user_prompt=context,
            temperature=0.3,
        )
        queries = [
            RetrievalQuery(**q) for q in queries_data.get("queries", [])
        ]

        # --- 2. Execute searches ---
        all_sources: list[Source] = []
        for q in queries:
            try:
                sources = await web_search(q.query)
                all_sources.extend(sources)
            except Exception as e:
                logger.warning("Search failed for query '%s': %s", q.query, e)

        # Deduplicate by URL
        seen_urls: set[str] = set()
        unique_sources: list[Source] = []
        for s in all_sources:
            if s.url not in seen_urls:
                seen_urls.add(s.url)
                unique_sources.append(s)

        # --- 3. Summarise round ---
        source_text = "\n\n".join(
            f"[{s.title}]({s.url}) — {s.snippet}" for s in unique_sources[:20]
        )
        summary_data = await chat_completion_json(
            system_prompt=ROUND_SUMMARY_SYSTEM,
            user_prompt=(
                f"Round {round_num} focus: {focus}\n\n"
                f"Search results:\n{source_text}\n\n"
                f"Prior context:\n{context}"
            ),
            max_tokens=3000,
        )

        # Parse entities & relationships
        new_entities = [
            Entity(**e) for e in summary_data.get("new_entities", [])
        ]
        new_relationships_raw = summary_data.get("new_relationships", [])
        new_relationships: list[Relationship] = []
        for r in new_relationships_raw:
            # Map source/target names to IDs
            src_id = _find_entity_id(r.get("source_entity", ""), all_entities + new_entities)
            tgt_id = _find_entity_id(r.get("target_entity", ""), all_entities + new_entities)
            if src_id and tgt_id:
                new_relationships.append(
                    Relationship(
                        source_entity_id=src_id,
                        target_entity_id=tgt_id,
                        relationship_type=r.get("relationship_type", "related_to"),
                        description=r.get("description", ""),
                    )
                )

        result = RetrievalRoundResult(
            round_number=round_num,
            focus=focus,
            queries=queries,
            sources_found=unique_sources,
            findings_summary=summary_data.get("findings_summary", ""),
            new_entities=new_entities,
            new_relationships=new_relationships,
            next_round_triggers=summary_data.get("next_round_triggers", []),
        )

        prior_findings.append(result.findings_summary)
        all_entities.extend(new_entities)

        yield result


def _build_context(
    framing: EventFraming,
    prior_findings: list[str],
    entities: list[Entity],
) -> str:
    parts = [
        f"Core event: {framing.core_event}",
        f"What: {framing.what}",
        f"Who: {', '.join(framing.who)}",
        f"Where: {', '.join(framing.where)}",
        f"When: {framing.when}",
        f"Why: {framing.why}",
        f"How: {framing.how}",
        f"Significance: {framing.so_what}",
    ]
    if prior_findings:
        parts.append("\n--- Prior round findings ---")
        for i, f in enumerate(prior_findings, 1):
            parts.append(f"Round {i}: {f}")
    if entities:
        parts.append("\n--- Known entities ---")
        for e in entities[:30]:
            parts.append(f"- {e.name} ({e.entity_type})")
    return "\n".join(parts)


def _find_entity_id(name: str, entities: list[Entity]) -> str | None:
    name_lower = name.lower()
    for e in entities:
        if e.name.lower() == name_lower:
            return e.id
    return None
